# Generated by Django 5.1.2 on 2024-10-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winxAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
