# Generated by Django 5.1.2 on 2024-11-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winxAPP', '0002_personaje_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='directora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='localizacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='primeraAparicion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='afiliacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='clase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='cumpleaños',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='poderes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temporada',
            name='fechaEstreno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporada',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporada',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporada',
            name='numeroEpisodios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporada',
            name='sinopsis',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
