# Generated by Django 5.1.2 on 2024-11-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winxAPP', '0006_remove_escuela_temporada_escuela_temporadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
